### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by ThePacificGamer** [masterfeizz/Xash3DS#2]
Theres no sound in the games, I've only tested Half-life but I plan to test more in the future, but so far no sound in the game

**Comment by masterfeizz** [comment]
You need to dump your dsp firmware. Use dsp1: https://github.com/zoogie/DSP1

**Comment by ThePacificGamer** [comment]
Heres a compressed file of my DSP dump
[dspfirm.zip](https://github.com/masterfeizz/Xash3DS/files/2948887/dspfirm.zip)

**Comment by ThePacificGamer** [comment]
Ok Dumped my DSP and sound works!
