### ISSUE TITLE
adding xash3ds causes it to make the sd card unreadable on my already shitty 3ds that has a faulty sd card scanner

### ISSUE THREAD

**Issue by SuperMarioROCKS** [masterfeizz/Xash3DS#26]
my 3ds is kinda old, has been dropped, and has issues scanning the sd card, but never would i thought that one application alone could cause the system to outright never read it, it always says it has write protection on when it doesnt
when i remove the folder, it can scan it again, but will never scan it when the folder is in place with the game files

**Comment by Xenthio** [comment]
sounds like a 3ds issue and not an issue with this software, idk why you decided to open an issue for this.

**Comment by ghost** [comment]
probably flick the  locked switch on the side
