### ISSUE TITLE
25th anniversary update causes black screen.

### ISSUE THREAD

**Issue by Butterscotch96** [masterfeizz/Xash3DS#49]
The demo provided works completely fine but when I tried actual Half-Life it just sits on a black screen and I have to reboot my 3DS. If I had to make a guess I think it's because of the 25th anniversary update that added and changed a lot of things.

**Comment by Butterscotch-P1e** [comment]
I tried the steam-legacy build (old version) and still doesn't work.

**Comment by Butterscotch-P1e** [comment]
Never mind I forgot the extras.pak when doing the old version. Works fine. The 25th update still doesn't work.
