### ISSUE TITLE
Navigating the Menus are really slow

### ISSUE THREAD

**Issue by MialTheMimiga** [masterfeizz/Xash3DS#9]
Whenever i launch the game, after loading when i try to navigate the menu , it takes a while to move the cursor around to do anything.

**Comment by masterfeizz** [comment]
You are missing the extras.pak file. Download it in the release page and place it inside sdmc:/xash3d/valve.

**Comment by MialTheMimiga** [comment]
I solved it. and it was at the issue of two things.
A. you never specified that it had to be the steam version of Half Life.
B. this one is straight up my fault, but i was denser than a neutron star and put the xash3d folder under sdmc:/3ds instead of the root of the card.
